apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: admin-role
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: sergiusz.urbaniak
subjects:
  - kind: User
    name: sergiusz.urbaniak@gmail.com
roleRef:
  kind: ClusterRole
  name: admin-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: stefan.schimanski
subjects:
  - kind: User
    name: stefan.schimanski@gmail.com
roleRef:
  kind: ClusterRole
  name: admin-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: stefan.junker
subjects:
  - kind: User
    name: stefanjunker86@gmail.com
roleRef:
  kind: ClusterRole
  name: admin-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: oauth-users
  namespace: kube-system
data:
  whitelist: |
    stefan.schmianski@gmail.com
    sergiusz.urbaniak@gmail.com
    stefanjunker86@gmail.com
